name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to Bintray
      env:
        SERVER_PASSWORD: ${{ secrets.BINTRAY_API_KEY }}
      run: mvn -B -s settings.xml deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
